version: '2'

services:
  react-app:
    build: ../../react-app
    command: "yarn start"
    environment:
      - PORT=3000
    volumes:
      - ../../react-app:/react-app
      - /react-app/node_modules
    ports:
     - "3001:3000"

  mongodb:
      image: mongo:6.0
      environment:
        - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE:-testDb}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME:-admin}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD:?MONGO_DB_PASSWORD is required}
      volumes:
        - ./mongo-initdb:/docker-entrypoint-initdb.d:z
      ports:
        - "27017:27017"

  express-app:
    build: ../../express-app
    command: nodemon ./bin/www
    environment:
      - MONGO_DB_DATABASE=${MONGO_DB_DATABASE:-testDb}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME:-admin}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD:?MONGO_DB_PASSWORD is required}
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ../../express-app:/express-app
#      - backend-dependencies:/express-app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    restart: always

#node_modules volumes to avoid architecture issues
#volumes:
#  backend-dependencies:
#  frontend-dependencies:
